### PR TITLE
Issue 1247 sidebar, dropdown menu, language switcher

### PR DESCRIPTION
**Pull request by vern-gora**

### CODE REVIEW

**Review by Jura — APPROVED** [review]

**Comment by Jura** [comment]
@theadamparker , when you have a chance - can you check appearance, and especially for the [Language switcher](https://issue-1247-sidebar-dropdownm.design-system.pages.dev/?path=/story/components-ui-components-language-switcher--language-switcher&globals=backgrounds.value:transparent)? @vern-gora fixed it according to the recommendations, but the final result seems a bit awkward to me. What's your take?

**Comment by Jura** [comment]
@vern-gora, we need to fix keyboard navigation as well. It doesn't have a "hover" state, so we have to apply the same treatment to ":active" selector as for ":hover". Test scenario - switch to the small screen and use keyboard to activate the widget.
Another issue is the hover effect on the top element of the Language switcher on small screens - it becomes shaded with blue when you put mouse over and it shoudn't:
image

**Comment by Jura** [comment]
Feedback from @theadamparker: colors treatment for all widgets is good, we shall proceed with what we have now.

**Comment by vern-gora** [comment]
Fixed the keyboard navigation in the sidebar, dropdown menu and language switcher. Did smoke testing, everything looks good enough. If I missed something, let me know

**Review by Jura — APPROVED** [review]

**Pull request merged**
