### PR TITLE
930 accent color should be implemented as a global variable

### PR DESCRIPTION
**Pull request by paboden**
Accent color control is updated for the following elements and ready for review

## Components
[Author image](https://design.undp.org/?path=/story/foundation-images-author-image--author-image) (hover color)
[Author](https://design.undp.org/?path=/story/components-ui-components-authors-author--author) (hover color)
[Author card](https://design.undp.org/?path=/story/components-ui-components-authors-author-card--author-card) (hover color)
[Bio card](https://design.undp.org/?path=/story/components-ui-components-cards-bio-card--bio-card) (hover color)
[Content card with image](https://design.undp.org/?path=/story/components-ui-components-cards-content-card-with-image--with-image) (hover color)
[Content card without image with emphasize](https://design.undp.org/?path=/story/components-ui-components-cards-content-card-without-image-with-emphasize--with-emphasize)
[Publication module](https://design.undp.org/?path=/story/components-ui-components-cards-download-card--publication-module) (hover color)
[Card module](https://design.undp.org/?path=/story/components-ui-components-cards-download-card--card-module) (hover color)
[Featured card](https://design.undp.org/?path=/story/components-ui-components-cards-featured-card--featured-card) (hover color)
[Image reveal card](https://design.undp.org/?path=/story/components-ui-components-cards-image-reveal-card--image-reveal-card) (hover color)
[Publication card](https://design.undp.org/?path=/story/components-ui-components-cards-publication-card--publication-card) (hover color)
[Stats card](https://design.undp.org/?path=/story/components-ui-components-cards-stats-card--stats-card) (hover color)
[Pagewide featured content card](https://design.undp.org/?path=/story/components-ui-components-pagewide-featured-content-card--pagewide-featured-content-card) (hover color)
[Stats](https://design.undp.org/?path=/story/components-ui-components-stats--stats) (hover color)
[Stats card slider](https://design.undp.org/?path=/story/components-ui-components-stats-card-slider--stats-card-slider) (imports individual stats cards)
[Callout](https://design.undp.org/?path=/story/components-ui-components-text-callout--callout) (when the color background is used it should reference the global variable)

## Patterns
[Content cards](https://design.undp.org/?path=/story/patterns-card-grids-content-cards--content-cards) (imports content card with image)
[Content cards with and without images](https://design.undp.org/?path=/story/patterns-card-grids-content-cards-with-and-without-image--content-cards-with-and-without-image) (imports multiple cards)
[Featured cards](https://design.undp.org/?path=/story/patterns-card-grids-featured-cards--featured-cards) (imports featured card)
[Image reveal cards](https://design.undp.org/?path=/story/patterns-card-grids-image-reveal-cards--image-reveal-cards) (imports image reveal card)
[Stats slider (two rows)](https://design.undp.org/?path=/story/patterns-stats-slider-two-rows--stats-slider-two-rows) (imports stats card)
[Progress bar navigation](https://design.undp.org/?path=/story/utilities-progress-bar-navigation--progress-bar-navigation)

## Templates
All template pages

### CODE REVIEW

**Comment by Jura** [comment]
@paboden , I like the button on the toolbar for choosing color, this is good. However, implementation of that parameter is not exactly aligned with our intention. What it should do is to add ".accent-[color]" class to the topmost element relevant for content, in case of Storybook implementation it can be `<body>` tag, and all widgets inside that container will appear using that color without a need to update their markup. Main focus here is on setting this once for the entire container. Current implementation adds color code as class name to each widget, which is exactly what we wanted to avoid.
Another angle here is the following - every widget should follow the closest setting if provided. i mean if there is a `.accent-red`  class set on `<body>` element - every card should use reddish accent for hover effect. If one of the cards in that setup will have its own `.accent-green` class set - all cards should be red, but one - it has to follow more specific class and use green

**Review by Jura — CHANGES_REQUESTED** [review]
@paboden , I like the button on the toolbar for choosing color, this is good. However, implementation of that parameter is not exactly aligned with our intention. What it should do is to add ".accent-[color]" class to the topmost element relevant for content, in case of Storybook implementation it can be `<body>` tag, and all widgets inside that container will appear using that color without a need to update their markup. Main focus here is on setting this once for the entire container. Current implementation adds color code as class name to each widget, which is exactly what we wanted to avoid.
Another angle here is the following - every widget should follow the closest setting if provided. i mean if there is a `.accent-red`  class set on `<body>` element - every card should use reddish accent for hover effect. If one of the cards in that setup will have its own `.accent-green` class set - all cards should be red, but one - it has to follow more specific class and use green

**Comment by Jura** [comment]
@paboden , we need to make sure that **every** widget which is using accent color is following page level settings. For example, here https://930-accent-color-should-be-i.design-system.pages.dev/?path=/story/templates-project-page--project-page&globals=accent:red Stat cards are using red accent color, but Explore more widget (grid with a mix of Content cards) is still using default yellow:
image

And it is pretty random, but toolbar button is not appearing after several subsequent refreshes or traversing the storybook, quite hard to test other pages: 
image

**Comment by Jura** [comment]
@paboden , please resolve conflicts and also add compile and commit production .css and .js files as per other comment

**Comment by paboden** [comment]
Not ready for merging yet. Need to an issue on the country page.

**Comment by paboden** [comment]
@Jura This is ready for review once the dev build has finished.

**Review by Jura — COMMENTED** [review]
@paboden , why docs/js/swiper.min.js has been changed? I don't see any changes in source in that respect, but only in minified version, can you explain, pls?

**Review by theadamparker — CHANGES_REQUESTED** [review]
@paboden for the `Featured content card`, when the `image` option is used it is not showing a color gradient atop an image. See screen capture here of the current implementation vs. the correct approach. 


https://user-images.githubusercontent.com/2205158/223223323-312c9851-1f79-4c31-897d-53bbb97f6ea1.mov

**Review by Jura — APPROVED** [review]

**Review by theadamparker — APPROVED** [review]

**Pull request merged**
